services:
  - type: web
    name: shoping-mall-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_ATLAS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: PORTONE_REST_API_KEY
        sync: false
      - key: PORTONE_REST_API_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false

